name: Auto update

on:
  schedule:
    - cron: '37 19 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Save ssh key
        run: |
          echo "${{ secrets.SSH_KEY }}" | install -Dm400 /dev/stdin ~/.ssh/github

      - name: Install packages
        run: |
          sudo apt-get install openssh-client python3-setuptools

      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: JinnLynn/genpac
          path: genpac

      - uses: actions/checkout@v3
        with:
          repository: gfwlist/gfwlist
          path: gfwlist

      - run: |
          cd genpac
          sed 's/from collections import Callable/from collections.abc import Callable/g' -i $(grep 'from collections import Callable' . -rIl)
          sudo python3 setup.py install

      - name: Update
        run: |
          set -x

          cp ssh_config ~/.ssh/config
          git config user.name ${{ secrets.GIT_COMMIT_NAME }}
          git config user.email ${{ secrets.GIT_COMMIT_EMAIL }}

          genpac --pac-proxy "SOCKS5 127.0.0.1:1080" --gfwlist-url - --gfwlist-local gfwlist/gfwlist.txt -o gfwlist.pac
          sed '1,7d' -i gfwlist.pac

          git add gfwlist.pac
          git commit -m "[$(LANG=C date)] auto update" || exit 0

          [ -n "${{ secrets.READ_ONLY }}" ] && git show && exit 0

          git push origin master
